# Generated by Django 4.1.7 on 2023-03-27 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapDoSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_cap_do', models.CharField(max_length=256, unique=True, verbose_name='Mã cấp độ')),
                ('ten_cap_do', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tên cấp độ')),
                ('mieu ta', models.TextField(verbose_name='Miêu tả')),
            ],
            options={
                'verbose_name': 'Cấp độ sản phẩm',
                'verbose_name_plural': 'Cấp độ sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khu_vuc', models.CharField(max_length=256, unique=True, verbose_name='Mã khu vực')),
                ('ten_hien_thi', models.CharField(max_length=256, verbose_name='Tên hiển thị')),
                ('mieu_ta', models.TextField(verbose_name='Miêu tả')),
                ('description', models.CharField(blank=True, help_text='Khu vực được hiểu là một khu trong bản đồ quy hoạch tổng thể, có thể chứa các loại sản phảm tương tự nhau.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Khu vực',
                'verbose_name_plural': 'Khu vực',
            },
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_san_pham', models.CharField(max_length=256, unique=True, verbose_name='Mã sản phẩm')),
                ('mieu_ta', models.TextField(verbose_name='Miêu tả')),
            ],
            options={
                'verbose_name': 'Mã sản phẩm',
                'verbose_name_plural': 'Mã sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hang', models.CharField(max_length=256, unique=True, verbose_name='Mã hàng')),
                ('ten_ma_hang', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tên mã hàng')),
                ('ma_cap_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.capdosanpham', to_field='ma_cap_do', verbose_name='Mã cấp độ')),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.loaisanpham', to_field='ma_san_pham', verbose_name='Mã sản phẩm')),
            ],
            options={
                'verbose_name': 'Loại hàng',
                'verbose_name_plural': 'Loại hàng',
            },
        ),
        migrations.CreateModel(
            name='Mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hang', models.IntegerField(verbose_name='Vị trí hàng')),
                ('cot', models.IntegerField(verbose_name='Vị trí cột')),
                ('ma_mo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Mã mộ')),
                ('ma_hang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='haccanhvien.loaihang', to_field='ma_hang', verbose_name='Loại hàng')),
                ('ma_khu_vuc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='haccanhvien.khuvuc', to_field='ma_khu_vuc', verbose_name='Mã khu vực')),
            ],
            options={
                'verbose_name': 'Phần mộ',
                'verbose_name_plural': 'Phần mộ',
                'unique_together': {('hang', 'cot', 'ma_khu_vuc')},
            },
        ),
    ]
