# Generated by Django 4.1.7 on 2023-03-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapDoSanPham',
            fields=[
                ('ma_cap_do', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Mã cấp độ')),
                ('mieu ta', models.TextField(verbose_name='Miêu tả')),
            ],
        ),
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('ma_khu_vuc', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Mã khu vực')),
                ('ten_hien_thi', models.CharField(max_length=256, verbose_name='Tên hiển thị')),
                ('mieu_ta', models.TextField(verbose_name='Miêu tả')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('ma_san_pham', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('mieu_ta', models.TextField(verbose_name='Miêu tả')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('ma_hang', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Mã hàng')),
                ('ma_cap_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.capdosanpham')),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.loaisanpham')),
            ],
        ),
        migrations.CreateModel(
            name='Mo',
            fields=[
                ('ma_mo', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Mã mộ')),
                ('hang', models.IntegerField(verbose_name='Vị trí hàng')),
                ('cot', models.IntegerField(verbose_name='Vị trí cột')),
                ('ma_khu_vuc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='haccanhvien.khuvuc')),
            ],
            options={
                'unique_together': {('hang', 'cot', 'ma_khu_vuc')},
            },
        ),
    ]
