# Generated by Django 4.1.7 on 2023-03-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaisanpham',
            name='ten_san_pham',
            field=models.CharField(default='', max_length=256, verbose_name='Tên sản phẩm'),
            preserve_default=False,
        ),
    ]
