# Generated by Django 4.1.7 on 2023-03-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capdosanpham',
            options={'verbose_name': 'Cấp độ sản phẩm', 'verbose_name_plural': 'Cấp độ sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='khuvuc',
            options={'verbose_name': 'Khu vực', 'verbose_name_plural': 'Khu vực'},
        ),
        migrations.AlterModelOptions(
            name='loaihang',
            options={'verbose_name': 'Loại hàng', 'verbose_name_plural': 'Loại hàng'},
        ),
        migrations.AlterModelOptions(
            name='loaisanpham',
            options={'verbose_name': 'Mã sản phẩm', 'verbose_name_plural': 'Mã sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='mo',
            options={'verbose_name': 'Phần mộ', 'verbose_name_plural': 'Phần mộ'},
        ),
        migrations.AddField(
            model_name='mo',
            name='ma_hang',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='haccanhvien.loaihang', verbose_name='Loại hàng'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loaihang',
            name='ma_cap_do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.capdosanpham', verbose_name='Mã cấp độ'),
        ),
        migrations.AlterField(
            model_name='loaihang',
            name='ma_san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.loaisanpham', verbose_name='Mã sản phẩm'),
        ),
        migrations.AlterField(
            model_name='mo',
            name='ma_khu_vuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='haccanhvien.khuvuc', verbose_name='Mã khu vực'),
        ),
    ]
