# Generated by Django 4.1.7 on 2023-03-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0002_loaisanpham_ten_san_pham'),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dich_vu', models.CharField(max_length=256, unique=True, verbose_name='Tên dịch vụ')),
                ('ma_dich_vu', models.CharField(max_length=256, unique=True, verbose_name='Mã dịch vụ')),
                ('mieu_ta', models.TextField(blank=True, null=True, verbose_name='Miêu tả')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='ThanhPhanDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thanh_phan', models.CharField(max_length=256, unique=True, verbose_name='Tên thành phần')),
                ('mieu_ta', models.TextField(blank=True, null=True, verbose_name='Miêu tả')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_dich_vu', models.CharField(max_length=256, unique=True, verbose_name='Loại dịch vụ')),
                ('ma_loai_dich_vu', models.CharField(max_length=256, unique=True, verbose_name='Mã loại dịch vụ')),
                ('mieu_ta', models.TextField(blank=True, null=True, verbose_name='Miêu tả')),
                ('danh_sach_dich_vu', models.ManyToManyField(to='haccanhvien.dichvu', verbose_name='Danh sách dịch vụ')),
            ],
        ),
        migrations.AddField(
            model_name='dichvu',
            name='danh_sach_thanh_phan',
            field=models.ManyToManyField(blank=True, null=True, to='haccanhvien.thanhphandichvu', verbose_name='Danh sách thành phần'),
        ),
    ]
