# Generated by Django 4.1.7 on 2023-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0003_dichvu_thanhphandichvu_loaidichvu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaidichvu',
            options={'verbose_name': 'Loại Dịch vụ', 'verbose_name_plural': 'Loại Dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='thanhphandichvu',
            options={'verbose_name': 'Thành phần Dịch vụ', 'verbose_name_plural': 'Thành phần Dịch vụ'},
        ),
        migrations.AddField(
            model_name='thanhphandichvu',
            name='ma_thanh_phan',
            field=models.CharField(default='', max_length=256, unique=True, verbose_name='Mã thành phần'),
            preserve_default=False,
        ),
    ]
