# Generated by Django 4.1.7 on 2023-03-28 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0004_alter_loaidichvu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaidichvu',
            name='danh_sach_dich_vu',
        ),
        migrations.AddField(
            model_name='dichvu',
            name='loai_dich_vu',
            field=models.ForeignKey(default='BM', on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.loaidichvu', to_field='ma_loai_dich_vu'),
            preserve_default=False,
        ),
    ]
