# Generated by Django 4.1.7 on 2023-03-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0006_alter_dichvu_loai_dich_vu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaidichvu',
            old_name='loai_dich_vu',
            new_name='ten_loai_dich_vu',
        ),
    ]
