# Generated by Django 4.1.7 on 2023-03-29 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0007_rename_loai_dich_vu_loaidichvu_ten_loai_dich_vu'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanhphandichvu',
            name='ma_loai_dich_vu',
            field=models.ForeignKey(default='BM', on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.loaidichvu', to_field='ma_loai_dich_vu', verbose_name='Mã loại dịch vụ'),
            preserve_default=False,
        ),
    ]
