# Generated by Django 4.1.7 on 2023-03-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0009_tinhtrangmo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tinhtrangmo',
            options={'verbose_name': 'Tình trạng mộ', 'verbose_name_plural': 'Tình trạng mộ'},
        ),
        migrations.AddField(
            model_name='mo',
            name='tinh_trang_mo',
            field=models.ForeignKey(default='CT', on_delete=django.db.models.deletion.RESTRICT, to='haccanhvien.tinhtrangmo', to_field='ma_tinh_trang', verbose_name='Tình trạng mộ'),
            preserve_default=False,
        ),
    ]
