# Generated by Django 4.1.7 on 2023-04-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0011_donhang_khachmat_khachmua_kyuc_giaychungnhan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachmat',
            name='thong_tin_khac',
            field=models.TextField(verbose_name='Thông tin khác'),
        ),
    ]
