# Generated by Django 4.1.7 on 2023-04-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0013_alter_anhkyuc_options_alter_donhang_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachmua',
            old_name='ten_khach_mua',
            new_name='ten_khach',
        ),
    ]
