# Generated by Django 4.1.7 on 2023-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0014_rename_ten_khach_mua_khachmua_ten_khach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachmat',
            name='thong_tin_khac',
            field=models.TextField(blank=True, verbose_name='Thông tin khác'),
        ),
    ]
