# Generated by Django 4.1.7 on 2023-04-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0015_alter_khachmat_thong_tin_khac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyuc',
            name='ma_khach_hang',
        ),
        migrations.AddField(
            model_name='kyuc',
            name='khach_hang',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='haccanhvien.khachmat', verbose_name='Khách hàng'),
            preserve_default=False,
        ),
    ]
