# Generated by Django 4.1.7 on 2023-04-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0016_remove_kyuc_ma_khach_hang_kyuc_khach_hang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giaychungnhan',
            old_name='ma_don_hang',
            new_name='don_hang',
        ),
    ]
