# Generated by Django 4.1.7 on 2023-04-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0017_rename_ma_don_hang_giaychungnhan_don_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaychungnhan',
            name='don_hang',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='haccanhvien.donhang'),
        ),
    ]
