# Generated by Django 4.1.7 on 2023-04-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haccanhvien', '0018_alter_giaychungnhan_don_hang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinhtrangmo',
            old_name='loai_tinh_trang',
            new_name='ten_tinh_trang'
        ),
    ]
